<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Version>$(GlobalVersion)</Version>
	  <Company>$(GlobalCompany)</Company>
	  <Copyright>$(GlobalCopyright)</Copyright>
	  <Authors>$(GlobalAuthors)</Authors>
	  <Description>Plugin Handler for Lunatic Panel Engine</Description>
	  <PackageProjectUrl>https://github.com/mshimshon/LunaticPanel</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/mshimshon/LunaticPanel</RepositoryUrl>
	  <Configurations>Debug;Release;PipelineStart;PipelineStop</Configurations>
	 

  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="McMaster.NETCore.Plugins" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\LunaticPanel.Core.Abstraction\LunaticPanel.Core.Abstraction.csproj" />
	  <ProjectReference Include="..\LunaticPanel.Core.PluginValidator\LunaticPanel.Core.PluginValidator.csproj" />
	</ItemGroup>

</Project>
