apt:
  - "openssh-server"
  - "openssh-client" 
  - "tmux" 
  - "libicu-dev" 
services:
    lunaticpanel:
        dotnet_project: "./LunaticPanel.Hybrid/LunaticPanel.Hybrid.Web/LunaticPanel.Hybrid.Web.csproj"
        # https:// to the location of deb release file we want.
        # deb_url: "" 
        exec_start: "./LunaticPanel.Hybrid.Web"
        working_dir: "/usr/lib/lunatic_panel"
        description: "Lunatic Panel dashboard hosting."
        environment:
          - "ASPNETCORE_ENVIRONMENT=Development"
        show: true
        depends_on:
           - lpkg_localserver
    lpkg_localserver:
        dotnet_project: "./LunaticPanel.Package.LocalServer/LunaticPanel.Package.LocalServer.csproj"
        # https:// to the location of deb release file we want.
        # deb_url: "" 
        startup_parameters: "--urls \"http://localhost:5001;\""
        exec_start: "./LunaticPanel.Package.LocalServer"
        working_dir: "/usr/lib/lpkg_localserver"
        description: "Lunatic Panel Local Package Server"
        environment:
          - "ASPNETCORE_ENVIRONMENT=Development"
        show: true
plugins:
  - local: "./Plugins/PackageManager/LunaticPanel.PackageManager/LunaticPanel.PackageManager.csproj"
  #- id: LunaticPanel.Auth
  #  version: "1.2.0"
  #  source: "https://domain/lpkg/v1/"

    

# settings:
#   - file: ./assets/PluginA/file.json
#     to: /etc/lunaticpanel/plugins/PluginA/settings.json

