name: Release
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.sha }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      id-token: write
      contents: write    
    if: |
       github.event.workflow_run.conclusion == 'success' && 
       startsWith(github.event.workflow_run.head_branch, 'v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          mkdir -p "/tmp/artifacts/output"
          # Grabs the short tag name (e.g., v0.0.2)
          TAG="${{ github.event.workflow_run.head_branch }}"
          
          # Strips the leading 'v' to get just the numbers (e.g., 0.0.2)
          VERSION="${TAG#v}"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
          


      ###########################################################################
      # PUBLISH ARTIFACTS
      ###########################################################################

      - name: Publish LunaticPanel.Hybrid.Web (linux, not self-contained)
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          dotnet publish $GITHUB_WORKSPACE/src/LunaticPanel.Hybrid/LunaticPanel.Hybrid.Web/LunaticPanel.Hybrid.Web.csproj \
            -c Release -r linux-x64 --self-contained false -o /tmp/artifacts/web /p:AssemblyVersion=$VERSION /p:FileVersion=$VERSION /p:InformationalVersion=$VERSION
          tar -czf "/tmp/artifacts/output/lunaticpanel.${VERSION}.tar.gz" -C /tmp/artifacts/web .

      - name: Publish LunaticPanel.Package.Tool (self-contained)
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          dotnet publish $GITHUB_WORKSPACE/tools/LunaticPanel.Package.Tool/LunaticPanel.Package.Tool.csproj \
            -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o /tmp/artifacts/tool /p:AssemblyVersion=$VERSION /p:FileVersion=$VERSION /p:InformationalVersion=$VERSION
          tar -czf "/tmp/artifacts/output/lpkg_tool.${VERSION}.tar.gz" -C /tmp/artifacts/tool .

      - name: Publish LunaticPanel.Package.LocalServer (linux, not self-contained)
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          dotnet publish $GITHUB_WORKSPACE/tools/LunaticPanel.Package.LocalServer/LunaticPanel.Package.LocalServer.csproj \
            -c Release -r linux-x64 --self-contained false -o /tmp/artifacts/server-lite /p:AssemblyVersion=$VERSION /p:FileVersion=$VERSION /p:InformationalVersion=$VERSION
          tar -czf "/tmp/artifacts/output/lpkg-server-lite.${VERSION}.tar.gz" -C /tmp/artifacts/server-lite .


      ###########################################################################
      # PACK NUGET PACKAGES IN ORDER
      ###########################################################################

      - name: Pack NuGet packages
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          
          KEY_PROJECTS=(
            "src/LunaticPanel.Core.Analyzer/LunaticPanel.Core.Analyzer.csproj"
            "src/LunaticPanel.Core.Abstraction/LunaticPanel.Core.Abstraction.csproj"
            "src/LunaticPanel.Core.PluginValidator/LunaticPanel.Core.PluginValidator.csproj"
            "src/LunaticPanel.Core/LunaticPanel.Core.csproj"
            "src/LunaticPanel.Core.Extensions/LunaticPanel.Core.Extensions.csproj"
            "src/LunaticPanel.Core.Utils.Abstraction/LunaticPanel.Core.Utils.Abstraction.csproj"
            "src/LunaticPanel.Core.Utils/LunaticPanel.Core.Utils.csproj"
            "tools/LunaticPanel.DebugTool/LunaticPanel.DebugTool.csproj"
            "tools/LunaticPanel.Package.Server/LunaticPanel.Package.Server.csproj"
            "plugins/PackageManager/LunaticPanel.PackageManager.Keys/LunaticPanel.PackageManager.Keys.csproj"
            "src/LunaticPanel.Engine.Keys/LunaticPanel.Engine.Keys.csproj"
            # add more Keys projects here
          )

          for KEY in "${KEY_PROJECTS[@]}"; do
            ABSOLUTE_CSPROJ_PATH="${{ github.workspace }}/$KEY"
            dotnet pack "$ABSOLUTE_CSPROJ_PATH" -c Release -o "/tmp/artifacts/output" /p:Version=$VERSION
          done

      ###########################################################################
      # PACKAGE PLUGINS USING TOOL
      ###########################################################################
      - name: Package plugins
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          PLUGINS=(
            "$GITHUB_WORKSPACE/plugins/PackageManager/LunaticPanel.PackageManager/LunaticPanel.PackageManager.csproj"
          )
          

          for KEY in "${PLUGINS[@]}"; do
            FILE_NAME=$(basename "$KEY")
            FILE_NAME=$(basename "$KEY")
            PROJECT_NAME="${FILE_NAME%.csproj}"
            TARGET_BUILD_DIR="/tmp/artifacts/plugins_build/$PROJECT_NAME"
            mkdir -p "$TARGET_BUILD_DIR"
            dotnet build "$KEY" -c Release -o "$TARGET_BUILD_DIR" /p:FileVersion=$VERSION /p:InformationalVersion=$VERSION /p:Version=$VERSION /p:AssemblyVersion=$VERSION
            /tmp/artifacts/tool/LunaticPanel.Package.Tool pack --input "$TARGET_BUILD_DIR" --output "/tmp/artifacts/output" --version $VERSION
            EXPECTED_PKG="/tmp/artifacts/output/${PROJECT_NAME}.${VERSION}.lpkg"
            if [ -z "$EXPECTED_PKG" ] || [ ! -s "$EXPECTED_PKG" ]; then
               ls -R /tmp/artifacts/output
              echo "❌ Error: Packed file for ${PROJECT_NAME} version ${VERSION} was not generated or is empty!"
              exit 1
            else
              echo "✅ Verified: $(basename "$EXPECTED_PKG") exists and is valid."
            fi
          done
          ls -R /tmp/artifacts/output


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            /tmp/artifacts/output/*.*

  deploy_nuget:
    needs: release
    runs-on: ubuntu-latest
    environment: 
      name: production
    timeout-minutes: 360

    permissions:
      id-token: write  # Crucial for OIDC token request privileges
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          mkdir -p "/tmp/artifacts/output"
          # Grabs the short tag name (e.g., v0.0.2)
          TAG="${{ github.event.workflow_run.head_branch }}"
          
          # Strips the leading 'v' to get just the numbers (e.g., 0.0.2)
          VERSION="${TAG#v}"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Pack NuGet packages
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          
          KEY_PROJECTS=(
            "src/LunaticPanel.Core.Analyzer/LunaticPanel.Core.Analyzer.csproj"
            "src/LunaticPanel.Core.Abstraction/LunaticPanel.Core.Abstraction.csproj"
            "src/LunaticPanel.Core.PluginValidator/LunaticPanel.Core.PluginValidator.csproj"
            "src/LunaticPanel.Core/LunaticPanel.Core.csproj"
            "src/LunaticPanel.Core.Extensions/LunaticPanel.Core.Extensions.csproj"
            "src/LunaticPanel.Core.Utils.Abstraction/LunaticPanel.Core.Utils.Abstraction.csproj"
            "src/LunaticPanel.Core.Utils/LunaticPanel.Core.Utils.csproj"
            "tools/LunaticPanel.DebugTool/LunaticPanel.DebugTool.csproj"
            "tools/LunaticPanel.Package.Server/LunaticPanel.Package.Server.csproj"
            "plugins/PackageManager/LunaticPanel.PackageManager.Keys/LunaticPanel.PackageManager.Keys.csproj"
            "src/LunaticPanel.Engine.Keys/LunaticPanel.Engine.Keys.csproj"
          )

          for KEY in "${KEY_PROJECTS[@]}"; do
            ABSOLUTE_CSPROJ_PATH="${{ github.workspace }}/$KEY"
            dotnet pack "$ABSOLUTE_CSPROJ_PATH" -c Release -o "/tmp/artifacts/output" /p:Version=$VERSION
          done

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push all NuGet packages with retry
        uses: nick-invision/retry@v2
        with:
          max_attempts: 10
          retry_wait_seconds: 10
          command: |
            VERSION="${{ steps.get_version.outputs.version }}"
            for PKG in /tmp/artifacts/output/*.nupkg; do
              echo "Pushing $PKG"
              dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
            done
      - name: Wait for Package availability
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 18000
          retry_wait_seconds: 15
          max_attempts: 1200
          command: |
            VERSION="${{ steps.get_version.outputs.version }}"
            for PKG in /tmp/artifacts/output/*.nupkg; do
              PKG_NAME="${FILENAME%.*}"        # remove .nupkg
              PKG_NAME="${PKG_NAME%.*}"        # remove .VERSION
              PKG_NAME_LOWER=$(echo "$PKG_NAME" | tr '[:upper:]' '[:lower:]')
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_NAME_LOWER}/${VERSION}.json")
              [ "$STATUS" -eq 200 ] || exit 1
            done

      # - name: Push LunaticPanel.Core.Analyzer Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core.Analyzer"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login1.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core.Analyzer availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core.analyzer"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login2
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Core.Abstraction Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core.Abstraction"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login2.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core.Abstraction availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core.abstraction"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login3
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Core.PluginValidator Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core.PluginValidator"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login3.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core.PluginValidator availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core.pluginvalidator"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login4
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Core Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login4.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login5
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Core.Extensions Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core.Extensions"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login5.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core.Extensions availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core.extensions"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login6
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Core.Utils.Abstraction Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core.Utils.Abstraction"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login6.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core.Utils.Abstraction availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core.utils.abstraction"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login7
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Core.Utils Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Core.Utils"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login7.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Core.Utils availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.core.utils"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: lunaticpanel_debugtool
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.DebugTool Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.DebugTool"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.lunaticpanel_debugtool.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.DebugTool availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.debugTool"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login8
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Package.Server Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Package.Server"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login8.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Package.Server availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.package.server"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login9
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.PackageManager.Keys Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.PackageManager.Keys"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login9.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.PackageManager.Keys availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.packagemanager.keys"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1

      # - name: NuGet login (OIDC → temp API key)
      #   uses: NuGet/login@v1
      #   id: login10
      #   with:
      #     user: ${{ secrets.NUGET_USER }}

      # - name: Push LunaticPanel.Engine.Keys Package
      #   run: |
      #     VERSION="${{ steps.get_version.outputs.version }}"
      #     PKG_ID="LunaticPanel.Engine.Keys"
      #     dotnet nuget push "/tmp/artifacts/output/${PKG_ID}.${VERSION}.nupkg" --api-key ${{ steps.login10.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
      # - name: Wait for LunaticPanel.Engine.Keys availability
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 30
      #     retry_wait_seconds: 15
      #     max_attempts: 120
      #     command: |
      #       VERSION="${{ steps.get_version.outputs.version }}"
      #       PKG_LOWER="lunaticpanel.engine.keys"
      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.nuget.org/v3/registration5-gz-semver2/${PKG_LOWER}/${VERSION}.json")
      #       [ "$STATUS" -eq 200 ] || exit 1
